### ISSUE TITLE
Saving diagram as .png doesn't work at all

### ISSUE THREAD

**Issue by HardMax71** [ls1intum/Apollon#118] opened 2020-07-23 16:07 UTC
### Describe the bug

After saving a diagram (in my case - activity diagram) as .png, it doesn't save about 30% of the diagram and other 70% are depicted in the wrong way.

#### To Reproduce

1. Open Appolon and create activity diagram
2. File -> Export -> As PNG -> Save
3. Open saved .png.

#### Expected behavior

It's expected that the diagram in .png is the same as in the tab of the browser.

#### Screenshots

After step 1.
![image](https://user-images.githubusercontent.com/66359507/88309850-98d10b00-cd17-11ea-9773-c81ee067f1b9.png)

After step 2.
![image](https://user-images.githubusercontent.com/66359507/88309891-a8e8ea80-cd17-11ea-97b7-bd7e309b00c3.png)

After step 3.
![image](https://user-images.githubusercontent.com/66359507/88309932-bb632400-cd17-11ea-8068-1714741ddb49.png)

### Environment

<details><pre>
 - OS: Win10
 - Browser Chrome
 - Version 83
</pre></details>

**Comment by flodt** [comment] 2020-07-25 09:33
I experienced this as well.
The other diagram types seem to work fine, though, it seems to be only an issue with exporting activity diagrams as PNG. I can also reproduce the disappearing text.

**Comment by TobiasPr** [comment] 2020-07-31 15:30
Fixed in Apollon Standalone 0.1.7 / Apollon library 2.1.16

**Closed by TobiasPr** 2020-07-31 15:30 UTC
Labels: bug
