### ISSUE TITLE
Dragging connections results in wrong connection

### ISSUE THREAD

**Issue by LeonStaufer** [ls1intum/Apollon#98] opened 2020-05-07 09:19 UTC
### Describe the bug
When dragging one of the blue connection corners to that of another element, the resulting connection is not between those two connection corners but instead between two seemingly random ones.

#### To Reproduce
1. Create two elements (e.g. class)
2. Start dragging from one of the blue connection corners
3. Let go at another blue connection corner
4. Often times, the resulting connection is different than expected

#### Expected behavior
The connection to consistently match the one provided when dragging.

#### Screenshots
![Dragging the connections](https://i.imgur.com/6U24j7D.png)

![Resulting conneciton](https://i.imgur.com/xFL0SDi.png)

### Environment
<details><pre>
 - OS: elementary OS 5.1.4 Hera, Built on Ubuntu 18.04.4 LTS, Linux 4.15.0-99-generic
 - Browser Firefox 75.0
</pre></details>

#### Output in Web Console
none

**Comment by TobiasPr** [comment] 2020-05-12 07:58
@LeonStaufer  Please note that firefox is not fully supported. Please use chrome for now as a fix for the issue. We might support firefox better in the future. 

Duplicate of #87

**Closed by TobiasPr** 2020-05-12 07:58 UTC
Labels: Unsupported Browser, bug, duplicate
