### ISSUE TITLE
Drawing Lines

### ISSUE THREAD

**Issue by isleyenufuk** [ls1intum/Apollon#235] opened 2022-05-24 11:10 UTC
I dont know if it is wanted but it sure as hell is annoying, if you draw a relationship between two objects or whatever it snaps to a different edge of the desired object.

**Comment by krusche** [comment] 2022-05-25 01:02
Can you please provide more details?

**Comment by b-fein** [comment] 2022-05-25 20:48
I’d expect the association to be between the two blue half-circles I dragged between. Instead the line snaps most of the time to the top of the element, sometimes to other edges.
I’ve had several student complaints about that today as well.
 
https://user-images.githubusercontent.com/64250573/170363823-9b17d206-10f5-4d22-b1b6-fa626073671f.mp4

**Comment by minrows** [comment] 2022-05-26 23:42
Hi @b-fein, I am having a look at the issue. A question though, is it the firefox that you used to attach the provided example?

**Comment by b-fein** [comment] 2022-05-27 05:05
Thanks!
Yes it is the latest Firefox 100.

**Comment by minrows** [comment] 2022-05-27 14:32
Duplicate of https://github.com/ls1intum/Apollon/issues/87

**Comment by minrows** [comment] 2022-05-27 14:34
@b-fein, the issue will be fixed once [the PR](https://github.com/ls1intum/Apollon/pull/174) is merged.

On a side note, as firefox is not fully supported, please use another browser if possible. Thanks. 👍

**Comment by b-fein** [comment] 2022-05-27 14:38
Thanks a lot, I did not see that an issue and PR were already created.

I’m aware that non-Chrome browsers are not officially supported for Apollon. The students using it from within Artemis don’t, though.

**Closed** 2022-05-27 17:25 UTC
Labels: bug, duplicate

**Comment by BaumiCoder** [comment] 2022-06-07 08:32
I tested with the actual code from the develop branch local with yarn (version 1.22.15). The error in firefox 101.0 64-Bit (OS: Linux Mint) still appear. Is that already know or why #87 isn't closed yet?
